Machine use flags.

diff --git a/configs/Gentoo/hooks/pre_build b/configs/Gentoo/hooks/pre_build
--- a/configs/Gentoo/hooks/pre_build
+++ b/configs/Gentoo/hooks/pre_build
@@ -1,10 +1,16 @@
 #!/usr/bin/env bash
 
 system_files_path="$HOME/.config/rebos/system_files"
+system_files_tmp_path="$system_files_path/tmp"
 vct_path="$system_files_path/video_cards_template/$HOSTNAME"
 pkgs_use_path="$system_files_path/pkgs_use"
-make_conf_path="$system_files_path/make.conf"
+pkgs_use_tmp_path="$system_files_tmp_path/pkgs_use"
+pkgs_use_machine_path="$system_files_path/machine_use/$HOSTNAME"
+make_conf_path="$system_files_tmp_path/make.conf"
 make_conf_template_path="$system_files_path/make_conf_template/make.conf"
+
+[[ -d "$system_files_tmp_path" ]] || mkdir "$system_files_tmp_path"
+[[ -d "$system_files_tmp_path" ]] || exit 1
 
 if [[ -f "$vct_path" ]]; then
   echo "Found video cards template for machine."
@@ -12,6 +18,16 @@ else
   echo "Missing video cards template for machine."
 
   echo "Template must be located at: $vct_path"
+
+  exit 1
+fi
+
+if [[ -f "$pkgs_use_machine_path" ]]; then
+  echo "Found machine package use flags."
+else
+  echo "Missing machine package use flags."
+
+  echo "Machine use flags must be located at: $pkgs_use_machine_path"
 
   exit 1
 fi
@@ -31,11 +47,15 @@ new_make_conf="$(cat "$make_conf_template_path" | sed "s/%video_cards%/${video_c
 [[ -f "$make_conf_path" ]] && rm "$make_conf_path"
 echo "$new_make_conf" > "$make_conf_path"
 
+[[ -f "$pkgs_use_tmp_path" ]] && rm "$pkgs_use_tmp_path"
+echo "$pkgs_use_path" > "$pkgs_use_tmp_path"
+echo "$pkgs_use_machine_path" >> "$pkgs_use_tmp_path"
+
 dfie_sudo /etc/portage/make.conf
 sudo cp "$make_conf_path" /etc/portage/make.conf
 
 dfie_sudo /etc/portage/package.use/pkgs
-sudo cp "$pkgs_use_path" /etc/portage/package.use/pkgs
+sudo cp "$pkgs_use_tmp_path" /etc/portage/package.use/pkgs
 
 autounmask_path="/etc/portage/package.accept_keywords/zzz_autounmask"
 
